# Generated by Django 3.0.5 on 2020-09-14 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=200)),
                ('water_line_compatible', models.BooleanField()),
                ('product_type', models.CharField(max_length=200)),
                ('coffee_flavor', models.CharField(max_length=200)),
                ('pack_size', models.CharField(max_length=200)),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Product')),
            ],
        ),
    ]
