# Generated by Django 3.0.5 on 2020-09-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='coffee_flavor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='options',
            name='machine',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='options',
            name='pack_size',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='options',
            name='product_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
