# Generated by Django 3.0.5 on 2020-09-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_auto_20200914_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
