# Generated by Django 3.0.5 on 2020-09-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_options_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='product_name',
        ),
        migrations.AddField(
            model_name='options',
            name='prudect_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
