# Generated by Django 3.0.5 on 2020-09-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_auto_20200914_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='prudect_name',
            new_name='product_name',
        ),
    ]
