# Generated by Django 3.0.5 on 2020-09-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='machine',
            field=models.CharField(choices=[('small', 'small'), ('large', 'large'), ('espresso', 'Espresso')], default='large', max_length=20),
        ),
    ]
