# Generated by Django 3.0.5 on 2020-09-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_auto_20200915_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='options',
            name='product_type',
        ),
        migrations.AddField(
            model_name='options',
            name='machines',
            field=models.CharField(choices=[('small', 'small coffee'), ('large', 'large coffee'), ('espresso', 'Espresso')], default='large', max_length=20),
        ),
        migrations.AddField(
            model_name='options',
            name='pods',
            field=models.CharField(choices=[('small', 'small coffee'), ('large', 'large coffee'), ('espresso', 'Espresso')], default='espresso', max_length=20),
        ),
        migrations.AlterField(
            model_name='options',
            name='coffee_flavor',
            field=models.CharField(choices=[('vanela', 'vanela'), ('caramel', 'Caramel'), ('psi', 'PSI'), ('macha', 'Mocha'), ('hazelnut', 'Hazelnut')], default='caramel', max_length=20),
        ),
        migrations.AlterField(
            model_name='options',
            name='pack_size',
            field=models.CharField(choices=[('1 dozen', '1 dozen'), ('3 dozen', '3 dozen'), ('5 dozen', '5 dozen'), ('7 dozen', '7 dozen')], default='3 dozen', max_length=20),
        ),
        migrations.AlterField(
            model_name='options',
            name='product_name',
            field=models.CharField(max_length=20),
        ),
    ]
