# Generated by Django 3.0.5 on 2020-09-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_auto_20200915_0425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RenameField(
            model_name='options',
            old_name='options',
            new_name='product',
        ),
    ]
