# Generated by Django 3.0.5 on 2020-09-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0010_auto_20200915_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machines',
            new_name='Machines_Options',
        ),
        migrations.RenameModel(
            old_name='Options',
            new_name='Pods_Options',
        ),
    ]
