# Generated by Django 3.0.5 on 2020-09-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0011_auto_20200915_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pods_options',
            name='coffee_flavor',
            field=models.CharField(choices=[('vanila', 'vanila'), ('caramel', 'Caramel'), ('psi', 'PSI'), ('macha', 'Mocha'), ('hazelnut', 'Hazelnut')], max_length=20),
        ),
    ]
