# Generated by Django 3.0.5 on 2020-09-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0012_auto_20200915_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machines_options',
            old_name='product',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='pods_options',
            old_name='product',
            new_name='choice',
        ),
    ]
