# Generated by Django 3.0.5 on 2020-09-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0014_auto_20200915_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='coffee_flavor',
            field=models.CharField(choices=[('base model', 'base model'), ('premium model', 'premium model'), ('deluxe model', 'deluxe model')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pods',
            name='coffee_flavor',
            field=models.CharField(choices=[('vanila', 'vanila'), ('caramel', 'caramel'), ('psi', 'psi'), ('macha', 'mocha'), ('hazelnut', 'hazelnut')], max_length=20),
        ),
    ]
