# Generated by Django 3.0.5 on 2020-09-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0015_auto_20200916_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pods',
            old_name='pods_choice',
            new_name='models',
        ),
    ]
