# Generated by Django 3.0.5 on 2020-09-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0016_auto_20200916_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pods',
            old_name='models',
            new_name='product',
        ),
    ]
