# Generated by Django 3.0.5 on 2020-09-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0017_auto_20200916_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machines',
            old_name='machine_choice',
            new_name='product',
        ),
    ]
